sonar.projectKey=camel-country-summary
sonar.projectName=Camel Country Summary API
sonar.projectVersion=1.0.0

# Diretórios de fonte
sonar.sources=src/main
sonar.tests=src/test

# Linguagem
sonar.language=java

# Exclusões
sonar.exclusions=**/target/**,**/*.test.java

# Cobertura de testes
sonar.java.coveragePlugin=jacoco
sonar.jacoco.reportPaths=target/jacoco.exec

# Regras de qualidade
sonar.qualitygate.wait=true

