receivers:
  otlp:
    protocols:
      http:

exporters:
  debug:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp]
